### ISSUE TITLE
请问友链是怎么设置的QWQ

### ISSUE THREAD

**Issue by Zchengtui** [Halyul/homepage#2]
在上个Issue( #1 )中你说的写死的问题...不存在的...
![20170720140429](https://user-images.githubusercontent.com/30227432/28402825-736f6968-6d54-11e7-9ff5-94f12a69782c.png)，不过实在没能从代码中分析出友链那个文件的格式QAQ

**Comment by Zchengtui** [comment]
@Halyul and @EYHN

**Comment by Halyul** [comment]
格式同[hexo-theme-mdui](github.com/halyul/hexo-theme-mdui) 
文档在[这](halyul.github.io/theme-mdui-docs)
毕竟我懒 数据是通用的当然是美滋滋的啦

**Comment by Zchengtui** [comment]
OOOOK

**Comment by Zchengtui** [comment]
不对啊，我记得还可以放出来的...按那样写的话全部在`更多`里

**Comment by Halyul** [comment]
放首页的加`index: true`
